<?php // this is an autogenerated file - do not edit (created Thu, 09 Sep 2010 10:25:22 +0200)
spl_autoload_register(
   function($class) {
      static $classes = array(
         'spriebsch\\hash\\dummy' => '/_testdata/Dummy.php',
         'spriebsch\\hash\\hashtest' => '/HashTest.php'
      );
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
