<?php // this is an autogenerated file - do not edit (created Tue, 07 Sep 2010 09:19:14 +0200)
spl_autoload_register(
   function($class) {
      static $classes = array(
         'spriebsch\\hash\\exception' => '/Exception.php',
         'spriebsch\\hash\\hash' => '/Hash.php'
      );
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
